CREATE TABLE MMUSIC(
	MNUM INT PRIMARY KEY,
	MTITLE VARCHAR(100) NOT NULL,
	MARTIST VARCHAR(100) NOT NULL,
	MHIT INT DEFAULT 0
);
CREATE TABLE MUSER(
	UNUM INT PRIMARY KEY,
	USERID VARCHAR(20) NOT NULL,
	UPW VARCHAR(20) NOT NULL,
	UNAME VARCHAR(20) NOT NULL,
	ULASTMUSIC INT DEFAULT 0
);

SELECT * FROM MUSER;


